apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: emoy-webhook
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'

    spec:
      containerConcurrency: 1
      timeoutSeconds: 5
      serviceAccountName: emoy-webhook-app@emoy-webhook.iam.gserviceaccount.com
      containers:
        - image: asia-docker.pkg.dev/emoy-webhook/emoy-webhook/app:main
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: '1'
              memory: 128Mi

          env:
            - name: FIRESTORE_COLLECTION
              value: "emoy_webhook_cache"

            # - name: PUMA_PORT
            #   value: "8080"
            # - name: PUMA_WORKERS
            #   value: "1"
            # - name: PUMA_MIN_THREADS
            #   value: "1"
            # - name: PUMA_MAX_THREADS
            #   value: "5"

            # Get credentials from SecretManager
            # c.f. https://cloud.google.com/run/docs/configuring/secrets
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: SLACK_WEBHOOK_URL

  traffic:
    - percent: 100
      latestRevision: true
