version: "3"

services:
  app:
    build: .
    working_dir: "/app"
    environment:
      - SLACK_WEBHOOK_URL
      - SENTRY_DSN
      # - DEBUG_LOGGING=false
      # - PUMA_THREADS_MIN=0
      # - PUMA_THREADS_MAX=1
      # - PUMA_WORKERS=0
      # - PUMA_PORT=8080
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
