version: 2.1

orbs:
  codeclimate: sue445/codeclimate@volatile
  ruby-orbs: sue445/ruby-orbs@volatile
  heroku:    circleci/heroku@volatile
  slack:     circleci/slack@volatile

executors:
  default:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          RACK_ENV: test
          CC_TEST_REPORTER_ID: 73528f83b1cf108dfc952f026c4cef899c61308702e5824e7f21e92cf49a9ee2
          REDIS_URL: redis://127.0.0.1:6379/0
      - image: circleci/redis:alpine
    working_directory: ~/app

jobs:
  rspec:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v1-bundle"
      - codeclimate/with-cc-test-reporter:
          after_build_args: '--coverage-input-type simplecov'
          steps:
            - run: bundle exec rspec
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
      - heroku/deploy-via-git:
          name: "Deploy to prickathon-emoy-webhook"
          app-name: "prickathon-emoy-webhook"
          context: Heroku
          requires:
            - rspec
          filters:
            branches:
              only: master
          post-deploy:
            - slack/notify:
                event: fail
                template: basic_fail_1
