version: 2.1

orbs:
  codeclimate: sue445/codeclimate@volatile
  ruby-orbs: sue445/ruby-orbs@volatile
  slack:     circleci/slack@3

executors:
  default:
    docker:
      - image: cimg/ruby:3.1
        environment:
          RACK_ENV: test
          CC_TEST_REPORTER_ID: 73528f83b1cf108dfc952f026c4cef899c61308702e5824e7f21e92cf49a9ee2
          REDIS_URL: redis://127.0.0.1:6379/0
      - image: cimg/redis:6.2
    working_directory: ~/app

jobs:
  rspec:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v1-bundle"
      - run:
          name: Install firebase emulator
          command: |
            set -xe
            sudo wget https://firebase.tools/bin/linux/latest -O /usr/local/bin/firebase --quiet
            sudo chmod 755 /usr/local/bin/firebase
            firebase setup:emulators:firestore

      - codeclimate/with-cc-test-reporter:
          after_build_args: '--coverage-input-type simplecov'
          steps:
            - run: firebase --project test emulators:exec --only firestore "bundle exec rspec"
      - slack/notify-on-failure

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
