name: test

on:
  push:
    branches:
      - main

  # Run builds for any PRs.
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "examples/**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true

      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version-file: .tool-versions

      - name: Install firebase emulator
        run: |
          set -xe
          sudo wget https://firebase.tools/bin/linux/latest -O /usr/local/bin/firebase --quiet
          sudo chmod 755 /usr/local/bin/firebase
          firebase setup:emulators:firestore

      - run: firebase --project test emulators:exec --only firestore "bundle exec rspec"
        env:
          RACK_ENV: test
          REDIS_URL: redis://127.0.0.1:${{ job.services.redis.ports['6379'] }}/0

      - name: Integration test
        run: |
          set -xe
          bundle exec puma -C config/puma.rb &
          
          # FIXME: Wait for booting
          sleep 3

          # Check status code
          curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/ | grep "200"

          pid=$(jobs -l | grep puma | awk '{print $2}')
          kill -9 $pid

      - name: Slack Notification
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}

  all-pass-test:
    if: always()

    needs:
      - test

    runs-on: ubuntu-slim

    steps:
      - name: check dependent jobs
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
